name: Periodic health check

on:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed application URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-broken-lake-7732.fly.dev/'
          follow-redirect: false
          max-attempts: 1
