name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Print current date
        run: date

      - name: Print current directory content
        run: ls -l
