name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-20.04 # I don't feel like experimenting with the latest version
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
