name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  # Release only on push/merge and only if the commit message doesn't contain '#skip'
  RELEASE: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')}}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    outputs:
      release: ${{ env.RELEASE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        if: ${{ env.RELEASE == 'true' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # notify Discord channel about failed build
      # - name: Build failure
      #   uses: BubbleProd/discord-webhook-notify@v2
      #   if: ${{ env.RELEASE == 'true' && failure() }}
      #   with:
      #     severity: error
      #     text: 'Build failed'
      #     # Blame head commit in case there are multiple
      #     description: >
      #       commit: ${{ github.event.head_commit.url }} by
      #       ${{ github.event.head_commit.author.username }} broke the build :(
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    # Make sure pipeline finishes its run first
    needs: [deployment_pipeline]
    if: ${{ needs.deployment_pipeline.outputs.release == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # should be 1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          # DRY_RUN: true # Use this to test the action without creating or tagging the release
      # notify Discord channel about failed build
      # - name: Build failure
      #   uses: BubbleProd/discord-webhook-notify@v2
      #   if: ${{ env.RELEASE == 'true' && failure() }}
      #   with:
      #     severity: error
      #     text: 'Build failed'
      #     # Blame head commit in case there are multiple
      #     description: >
      #       commit: ${{ github.event.head_commit.url }} by
      #       ${{ github.event.head_commit.author.username }} broke the build :(
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment success 1
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ env.RELEASE == 'true' && success() }}
        with:
          severity: info
          text: Build succeeded
          description: A new version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment success 2
        uses: Retr0-01/better-discord-notification@main
        if: ${{ env.RELEASE == 'true' && success() }}
        with:
          embed-color: '65280'
          msg-content: 'A new version of Pokedex deployed'
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          ignore-hidden: 'false'
      - name: Deployment success 3
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
          args: 'A new version of Pokedex deployed'
